-- MySQL Script generated by MySQL Workbench
-- Fri Jun 24 21:52:18 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema online_courses
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema online_courses
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `online_courses` DEFAULT CHARACTER SET utf8 ;
USE `online_courses` ;

-- -----------------------------------------------------
-- Table `online_courses`.`cours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_courses`.`cours` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sigle` INT NOT NULL,
  `titre` VARCHAR(45) NOT NULL,
  `idProfesseur` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_courses`.`etudiant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_courses`.`etudiant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(12) NOT NULL DEFAULT '',
  `prenom` VARCHAR(45) NULL DEFAULT NULL,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `sexe` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_courses`.`professeur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_courses`.`professeur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_courses`.`etudiant_cours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_courses`.`etudiant_cours` (
  `etudiant_id` INT NOT NULL,
  `cours_id` INT NOT NULL,
  PRIMARY KEY (`etudiant_id`, `cours_id`),
  CONSTRAINT `fk_etudiant_has_cours_etudiant`
    FOREIGN KEY (`etudiant_id`)
    REFERENCES `online_courses`.`etudiant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_etudiant_has_cours_cours1`
    FOREIGN KEY (`cours_id`)
    REFERENCES `online_courses`.`cours` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- CREATE INDEX `fk_etudiant_has_cours_cours1_idx` ON `online_courses`.`etudiant_cours` (`cours_id` ASC) VISIBLE;

-- CREATE INDEX `fk_etudiant_has_cours_etudiant_idx` ON `online_courses`.`etudiant_cours` (`etudiant_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `online_courses`.`professeur_cours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_courses`.`professeur_cours` (
  `professeur_id` INT NOT NULL,
  `cours_id` INT NOT NULL,
  PRIMARY KEY (`professeur_id`, `cours_id`),
  CONSTRAINT `fk_professeur_has_cours_professeur1`
    FOREIGN KEY (`professeur_id`)
    REFERENCES `online_courses`.`professeur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professeur_has_cours_cours1`
    FOREIGN KEY (`cours_id`)
    REFERENCES `online_courses`.`cours` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- CREATE INDEX `fk_professeur_has_cours_cours1_idx` ON `online_courses`.`professeur_cours` (`cours_id` ASC) VISIBLE;

-- CREATE INDEX `fk_professeur_has_cours_professeur1_idx` ON `online_courses`.`professeur_cours` (`professeur_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
